### ISSUE TITLE
Failed loading boilerplate: open k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#55]

**Comment by shenkonghui** [comment]
```
sudo $GOPATH/src/k8s.io/code-generator/generate-groups.sh all /Users/shenkonghui/src/work/middleware-controller/pkg/generated  /Users/shenkonghui/src/work/middleware-controller/api middlewares.harmonycloud.cn:v1
```
提示
```
F0325 14:07:01.112072    6058 deepcopy.go:131] Failed loading boilerplate: open k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc0000241e0, 0x99, 0xe9)
        /Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x15702a0, 0xc000000003, 0x0, 0x0, 0xc000013a40, 0x1431dbf, 0xb, 0x83, 0x0)
        /Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:975 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x15702a0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1370195, 0x1e, 0xc000056a60, 0x1, ...)
        /Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:750 +0x191
k8s.io/klog/v2.Fatalf(...)
        /Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1502
k8s.io/gengo/examples/deepcopy-gen/generators.Packages(0xc0000139d0, 0xc000116fa0, 0x134db92, 0x6, 0xc0000139d0)
        /Users/shenkonghui/go/pkg/mod/k8s.io/gengo@v0.0.0-20201113003025-83324d819ded/examples/deepcopy-gen/generators/deepcopy.go:131 +0x146
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc000116fa0, 0xc000125e38, 0x134db92, 0x6, 0x137acb8, 0x0, 0x0)
        /Users/shenkonghui/go/pkg/mod/k8s.io/gengo@v0.0.0-20201113003025-83324d819ded/args/args.go:206 +0x1b7
main.main()
        /Users/shenkonghui/go/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go:77 +0x4cb

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x15702a0)
        /Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
        /Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:417 +0xdf

```

**Comment by shenkonghui** [comment]
直接执行，提示有，但是并没有生成代码
```
 $GOPATH/src/k8s.io/code-generator/generate-groups.sh all /Users/shenkonghui/src/work/middleware-controller/pkg/generated  /Users/shenkonghui/src/work/middleware-controller/api middlewares.harmonycloud.cn:v1
Generating deepcopy funcs
Generating clientset for middlewares.harmonycloud.cn:v1 at /Users/shenkonghui/src/work/middleware-controller/pkg/generated/clientset
Generating listers for middlewares.harmonycloud.cn:v1 at /Users/shenkonghui/src/work/middleware-controller/pkg/generated/listers
Generating informers for middlewares.harmonycloud.cn:v1 at /Users/shenkonghui/src/work/middleware-controller/pkg/generated/informers

```

**Comment by shenkonghui** [comment]
#56

**Comment by heyu1207** [comment]
我碰到了一样的报错，请问是怎么解决的呢？

**Comment by shenkonghui** [comment]
> 我碰到了一样的报错，请问是怎么解决的呢？

好像即使是用了go mod管理项目，这个项目也要放到gopath目录下面才行，而且不能包含多个gopath

**Comment by heyu1207** [comment]
我是用的go install，这个项目就下载到了gopath/pkg/mod下面，然后我是在这个下面运行的那个脚本，我的gopath变量确实是只有一个值的。因为我刚接触go，可以说的详细一点吗？

**Comment by shenkonghui** [comment]
> 我是用的go install，这个项目就下载到了gopath/pkg/mod下面，然后我是在这个下面运行的那个脚本，我的gopath变量确实是只有一个值的。因为我刚接触go，可以说的详细一点吗？

关闭go mod
export GO111MODULE=off ，然后试试看
需要安装到$gopath/src 目录下面

**Comment by heyu1207** [comment]
我把code-generator移动到src目录后执行确实不再报这个错了，但是只生成了clientset。我看了您在#56的回答，但我感觉自己的目录应该没错。
目录结构：apis/heyu/v1
执行命令：[root@localhost src]# k8s.io/code-generator/generate-groups.sh all nmr_controller/pkg/client nmr_controller/pkg/apis heyu:v1

**Comment by shenkonghui** [comment]
> 我把code-generator移动到src目录后执行确实不再报这个错了，但是只生成了clientset。我看了您在#56的回答，但我感觉自己的目录应该没错。 目录结构：apis/heyu/v1 执行命令：[root@localhost src]# k8s.io/code-generator/generate-groups.sh all nmr_controller/pkg/client nmr_controller/pkg/apis heyu:v1

目录结构发我看一下吧

**Comment by heyu1207** [comment]
![image](https://user-images.githubusercontent.com/43037766/195295829-03388b98-1f0b-4e35-bed5-9ad95da6e9fc.png)
我是仿照的这篇博客：https://blog.csdn.net/boling_cavalry/article/details/88924194
只把里面的组名bolingcavalry修改成了heyu

**Comment by shenkonghui** [comment]
> ![image](https://user-images.githubusercontent.com/43037766/195295829-03388b98-1f0b-4e35-bed5-9ad95da6e9fc.png) 我是仿照的这篇博客：https://blog.csdn.net/boling_cavalry/article/details/88924194 只把里面的组名bolingcavalry修改成了heyu

1.检查一下 k8s.io/kubernetes版本和code-generator是否一致
2.检查一下api文件中k8s:deepcopy这类配置有没有

**Comment by zhoucheng45** [comment]
> 
需要指定 --go-header-file  参数。  可以指定成 sample-controller/hack/boilerplate.go.txt

**Comment by THMAIL** [comment]
> > 
> 
> 需要指定 --go-header-file 参数。 可以指定成 sample-controller/hack/boilerplate.go.txt

正解，成功解决

**Comment by zhoucheng45** [comment]
您好，您的邮件我已经收到！请放心！，我会尽快回复！祝工作顺利，身体健康！

**Comment by hicker-kin** [comment]
sample-controller是那儿来的啊？我怎么没找到？

**Comment by zhoucheng45** [comment]
您好，您的邮件我已经收到！请放心！，我会尽快回复！祝工作顺利，身体健康！
