### ISSUE TITLE
code-generator问题汇总

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#56]

**Comment by shenkonghui** [comment]
```
 ~/go/src/k8s.io/sample-controller$  ./hack/verify-codegen.sh
Generating deepcopy funcs
F0325 14:51:03.835265   12415 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1.Foo
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc000236300, 0xab, 0xfb)
	/Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x15702a0, 0xc000000003, 0x0, 0x0, 0xc00025e2a0, 0x1431dbf, 0xb, 0x375, 0x0)
	/Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:975 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x15702a0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1375c65, 0x2a, 0xc000270ba0, 0x3, ...)
	/Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:750 +0x191
k8s.io/klog/v2.Fatalf(...)
	/Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1502
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).doStruct(0xc000240200, 0xc000252180, 0xc000214e10)
	/Users/shenkonghui/go/pkg/mod/k8s.io/gengo@v0.0.0-20201113003025-83324d819ded/examples/deepcopy-gen/generators/deepcopy.go:885 +0x906
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).generateFor(0xc000240200, 0xc000252180, 0xc000214e10)
	/Users/shenkonghui/go/pkg/mod/k8s.io/gengo@v0.0.0-20201113003025-83324d819ded/examples/deepcopy-gen/generators/deepcopy.go:695 +0xcf
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).GenerateType(0xc000240200, 0xc00025e150, 0xc000252180, 0x13c3ca0, 0xc000216800, 0x0, 0x7ffeefbff433)
	/Users/shenkonghui/go/pkg/mod/k8s.io/gengo@v0.0.0-20201113003025-83324d819ded/examples/deepcopy-gen/generators/deepcopy.go:608 +0xf98
k8s.io/gengo/generator.(*Context).executeBody(0xc00025e150, 0x13c3740, 0xc00024c1b0, 0x13cc318, 0xc000240200, 0x2c0, 0xc0001c5bc0)
	/Users/shenkonghui/go/pkg/mod/k8s.io/gengo@v0.0.0-20201113003025-83324d819ded/generator/execute.go:306 +0x122
k8s.io/gengo/generator.(*Context).ExecutePackage(0xc00025e000, 0x7ffeefbff489, 0x17, 0x13ca890, 0xc00022e630, 0x0, 0x0)
	/Users/shenkonghui/go/pkg/mod/k8s.io/gengo@v0.0.0-20201113003025-83324d819ded/generator/execute.go:267 +0xb98
k8s.io/gengo/generator.(*Context).ExecutePackages(0xc00025e000, 0x7ffeefbff489, 0x17, 0xc00022a9b0, 0x1, 0x1, 0x0, 0x28)
	/Users/shenkonghui/go/pkg/mod/k8s.io/gengo@v0.0.0-20201113003025-83324d819ded/generator/execute.go:51 +0xc8
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc000112f00, 0xc0001c5e38, 0x134db92, 0x6, 0x137acb8, 0x0, 0x0)
	/Users/shenkonghui/go/pkg/mod/k8s.io/gengo@v0.0.0-20201113003025-83324d819ded/args/args.go:207 +0x1fa
main.main()
	/Users/shenkonghui/go/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go:77 +0x4cb

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x15702a0)
	/Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
	/Users/shenkonghui/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:417 +0xdf
```

解决方案：
将golang版本从1.16 降低成1.14

**Comment by shenkonghui** [comment]
注意事项：
1. 只能在gopath下面才生效，无法在go mod本地目录生成

**Comment by shenkonghui** [comment]
只生成clientset文件夹

```
bash "${CODEGEN_PKG}"/generate-groups.sh "deepcopy,client,informer,lister" \
  harmonycloud.cn/middleware-controller/pkg/generated harmonycloud.cn/middleware-controller/pkg/apis \
  rediscluster:v1alpha1 \
  --output-base "$(dirname "${BASH_SOURCE[0]}")/../../.." \
  --go-header-file "${SCRIPT_ROOT}"/hack/boilerplate.go.txt
```

注意 rediscluster:v1alpha1和api下面的目录是不是保存一致

**Comment by shenkonghui** [comment]
```
Generating deepcopy funcs
vendor/k8s.io/code-generator/generate-groups.sh: line 74: /Users/shenkonghui/go:/Users/shenkonghui/src/work/bin/deepcopy-gen: No such file or directory
```
设置多个gopath有问题
手动修改一下gopath

**Comment by shenkonghui** [comment]
旧项目(直接使用gopath+vendor进行依赖包管理的)，直接使用master的code-generator生成的代码兼容性有问题，需要确认k8s.io/kubernetes的版本，下载对应版本的code-generator
https://github.com/kubernetes/code-generator/releases
