### ISSUE TITLE
[zookeeper]java.lang.RuntimeException: My id 2 not in the peer list

### ISSUE THREAD

**Issue by shenkonghui** [shenkonghui/issue#88]
```
zk-zookeeper-0                                                   1/1     Running            0          7m42s   10.244.10.102    10.1.10.153-pcloud      <none>           <none>
zk-zookeeper-1                                                   0/1     CrashLoopBackOff   6          7m25s   10.244.132.164   10.1.10.151-pcloud      <none>           <none>
```
zk-zookeeper-1  日志如下
```
2021-06-25 03:45:52,214 [myid:2] - INFO  [main:QuorumPeer@2486] - quorum.cnxn.threads.size set to 20
2021-06-25 03:45:52,229 [myid:2] - INFO  [main:AbstractConnector@380] - Stopped ServerConnector@771a660{HTTP/1.1,[http/1.1]}{0.0.0.0:7000}
2021-06-25 03:45:52,231 [myid:2] - INFO  [main:ContextHandler@1016] - Stopped o.e.j.s.ServletContextHandler@69c81773{/,null,UNAVAILABLE}
2021-06-25 03:45:52,281 [myid:2] - ERROR [main:QuorumPeerMain@113] - Unexpected exception, exiting abnormally
java.lang.RuntimeException: My id 2 not in the peer list
        at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:1073)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:227)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:136)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
2021-06-25 03:45:52,284 [myid:2] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
2021-06-25 03:45:52,286 [myid:2] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1
```

**Comment by shenkonghui** [comment]
本质原因是由于 myid 和 zoo.cfg 不一致导致的，但是这里是通过zoo.cfg.dynamic 动态进行配置的


zk-0的myid和zoo.cfg如下
```
root@zk-zookeeper-0:/data# cat myid 
1
root@zk-zookeeper-0:/data# cat myid ^C
root@zk-zookeeper-0:/data# cat zoo.cfg.dynamic 
server.1=zk-zookeeper-0.zk-zookeeper-headless.middleware-test.svc.cluster.local:2888:3888:participant;2181
```
